// <auto-generated />
namespace TrashCollectors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class neednewmigrationforsomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(neednewmigrationforsomething));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041909113_need new migration for something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
