// <auto-generated />
namespace TrashCollectors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddisplaynamesincustomerandemployeemodelsDeletedbalancefromcustomermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddisplaynamesincustomerandemployeemodelsDeletedbalancefromcustomermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803292139130_added display names in customer and employee models. Deleted balance from customer model."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
